//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDB_MKII.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPDB_MKII.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add now.
        /// </summary>
        internal static string Button_AddNow {
            get {
                return ResourceManager.GetString("Button_AddNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you to configure the tag category..
        /// </summary>
        internal static string Dialog_CategoryEditor_Abstract {
            get {
                return ResourceManager.GetString("Dialog_CategoryEditor_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category.
        /// </summary>
        internal static string Dialog_CategoryEditor_Title_Add {
            get {
                return ResourceManager.GetString("Dialog_CategoryEditor_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category {0}.
        /// </summary>
        internal static string Dialog_CategoryEditor_Title_EditX {
            get {
                return ResourceManager.GetString("Dialog_CategoryEditor_Title_EditX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a folder to add to the library..
        /// </summary>
        internal static string Dialog_Folders_Browse_Description {
            get {
                return ResourceManager.GetString("Dialog_Folders_Browse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new folder has been added..
        /// </summary>
        internal static string Dialog_Folders_Message_Added_Folder {
            get {
                return ResourceManager.GetString("Dialog_Folders_Message_Added_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a label to recognize the folder by..
        /// </summary>
        internal static string Dialog_Folders_Message_EnterLabel {
            get {
                return ResourceManager.GetString("Dialog_Folders_Message_EnterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the folder was cancelled..
        /// </summary>
        internal static string Dialog_Folders_Status_CancelledAdding {
            get {
                return ResourceManager.GetString("Dialog_Folders_Status_CancelledAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folders have been removed from the list..
        /// </summary>
        internal static string Dialog_Folders_Status_FoldersDeleted {
            get {
                return ResourceManager.GetString("Dialog_Folders_Status_FoldersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new folder.
        /// </summary>
        internal static string Dialog_Folders_Title_AddFolder {
            get {
                return ResourceManager.GetString("Dialog_Folders_Title_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a text..
        /// </summary>
        internal static string Dialog_TextPrompt_Message {
            get {
                return ResourceManager.GetString("Dialog_TextPrompt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input.
        /// </summary>
        internal static string Dialog_TextPrompt_Title {
            get {
                return ResourceManager.GetString("Dialog_TextPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage folders.
        /// </summary>
        internal static string Dialog_Title_Folders {
            get {
                return ResourceManager.GetString("Dialog_Title_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPDB MKII.
        /// </summary>
        internal static string Dialog_Title_Main {
            get {
                return ResourceManager.GetString("Dialog_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the database..
        /// </summary>
        internal static string Message_Database_Connection_Failed {
            get {
                return ResourceManager.GetString("Message_Database_Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database {0} has been added..
        /// </summary>
        internal static string Status_Database_X_Added {
            get {
                return ResourceManager.GetString("Status_Database_X_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database {0} has been saved..
        /// </summary>
        internal static string Status_Database_X_Saved {
            get {
                return ResourceManager.GetString("Status_Database_X_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a database.
        /// </summary>
        internal static string Title_Add_Database {
            get {
                return ResourceManager.GetString("Title_Add_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a database.
        /// </summary>
        internal static string Title_Edit_Database {
            get {
                return ResourceManager.GetString("Title_Edit_Database", resourceCulture);
            }
        }
    }
}
